export const caseStudies = [
    {
        title: "DMart Islamabad Android Application & Website for E-Commerce and Home Health Services",
        slug: "dmart-islamabad-android-application-website",
        description: "To help expand its reach and streamline operations, DMart Islamabad, a growing e-commerce platform, required a scalable Android application and website with integrated home health services.",
        icon: "ShoppingCart",
    },
    {
        title: "Local Government Kpk iOS App & Website for Civic Awareness in Newly Merged Areas",
        slug: "local-government-kpk-ios-app-website",
        description: "To support the integration of newly merged tribal districts into Khyber Pakhtunkhwa's governance structure, an iOS app and website were developed to promote civic awareness.",
        icon: "Landmark",
    },
    {
        title: "Local Government Kpk Android App & Website for Public Awareness in Newly Merged Areas",
        slug: "local-government-kpk-android-app-website",
        description: "In support of the Government of Khyber Pakhtunkhwa's initiative, an Android app and website were built to empower citizens in newly merged tribal districts with public information.",
        icon: "Smartphone",
    },
    {
        title: "Audio-Pedia: Multilingual Legal Awareness Platform",
        slug: "audio-pedia-multilingual-legal-awareness-platform",
        description: "In collaboration with GIZ Pakistan, the Local Government of Khyber Pakhtunkhwa launched Audio-Pedia—a multilingual platform designed to spread legal awareness through audio content.",
        icon: "Volume2",
    },
    {
        title: "GPI Hayatabad, GPI Karak & GTC Charsadda",
        slug: "gpi-hayatabad-gpi-karak-gtc-charsadda",
        description: "Government Polytechnic Institutes Hayatabad and Karak, along with Government Technical College Charsadda, required digital systems to modernize academic and administrative operations.",
        icon: "GraduationCap",
    },
    {
        title: "Livestock & Dairy Farm Department",
        slug: "livestock-dairy-farm-department",
        description: "The Livestock & Dairy Development Department of Khyber Pakhtunkhwa of Khyber Pakhtunkhwa needed a centralized system to improve information sharing and operational efficiency.",
        icon: "Wheat",
    },
    {
        title: "Higher Education Department (HED)",
        slug: "higher-education-department-hed",
        description: "The Higher Education Department of Khyber Pakhtunkhwa required a comprehensive Management Information System to digitize institutional data and processes.",
        icon: "School",
    },
    {
        title: "WATSAN Cell (Gov Khyber Pakhtunkhwa)",
        slug: "watsan-cell-gov-khyber-pakhtunkhwa",
        description: "The WATSAN Cell needed a secure and reliable digital solution for sanitation monitoring and reporting across Khyber Pakhtunkhwa.",
        icon: "Droplets",
    },
    {
        title: "KP BOIT Official Website & Hosting Infrastructure",
        slug: "kp-boit-official-website-hosting-infrastructure",
        description: "The Board of Investment & Trade Khyber Pakhtunkhwa required a modern, responsive website and reliable hosting infrastructure to represent its mission and services.",
        icon: "Building2",
    },
    {
        title: "Agriculture University MIS and Web Portal",
        slug: "agriculture-university-mis-web-portal",
        description: "Agriculture University Peshawar needed a secure MIS and web portal to modernize student admissions, fee submission, and evaluation systems.",
        icon: "Database",
    },
    {
        title: "Modernizing of KPTEVTA Through ERP",
        slug: "modernizing-kptevta-through-erp",
        description: "KP TEVTA required a full-scale ERP system to streamline technical and vocational training operations across the province.",
        icon: "Factory",
    },
    {
        title: "School Management System of NIPHS",
        slug: "school-management-system-niphs",
        description: "New Islamia School & College partnered with IT Artificer to implement a full-featured School ERP covering academics, administration, and reporting.",
        icon: "BookOpen",
    },
    {
        title: "All-in-One ERP Solution for High-Volume Typing & Document Services",
        slug: "all-in-one-erp-solution-typing-document-services",
        description: "Dar Al Eitemad Center in the UAE partnered with IT Artificer to build a unified ERP system for high-volume typing, translation, and visa processing services.",
        icon: "ClipboardList",
    },
    {
        title: "E-Commerce Platform with Inventory & Delivery MIS for Retail Growth",
        slug: "e-commerce-platform-inventory-delivery-mis",
        description: "DMart Islamabad required an integrated e-commerce platform with inventory and delivery MIS to support retail growth and operational efficiency.",
        icon: "Truck",
    },
    {
        title: "Real-Time Disaster Alert & Forecasting Apps for Emergency Preparedness",
        slug: "real-time-disaster-alert-forecasting-apps",
        description: "The Provincial Disaster Management Authority partnered with IT Artificer to develop real-time disaster alert and forecasting applications.",
        icon: "AlertTriangle",
    },
    {
        title: "Strengthening Local Governance Through a Bilingual LMS & Civic Awareness Platform",
        slug: "strengthening-local-governance-bilingual-lms",
        description: "With support from WHH and WEPP-Cowater, a bilingual LMS and civic awareness platform was developed to digitally equip local governance institutions.",
        icon: "Globe",
    },
    {
        title: "Citizen-Centric Complaint Management System to Improve Local Governance",
        slug: "citizen-centric-complaint-management-system",
        description: "In collaboration with the International Rescue Committee, IT Artificer developed a complaint management system to improve public service delivery.",
        icon: "MessageSquareWarning",
    },
    {
        title: "Mission-Critical MIS for Operational Efficiency in Military Command",
        slug: "mission-critical-mis-operational-efficiency",
        description: "Frontier Corps KP North required a robust, secure MIS to support mission-critical operational and command-level efficiency.",
        icon: "ShieldCheck",
    },
    {
        title: "Digitizing International Healthcare Operations with a Unified ERP & Telemedicine Platform",
        slug: "digitizing-international-healthcare-operations-unified-erp",
        description: "UTP Medics partnered with IT Artificer to digitize healthcare operations through a unified ERP and telemedicine platform across multiple countries.",
        icon: "HeartPulse",
    },
    {
        title: "Ministry of Energy – Department of Explosives (Pakistan) National Explosives Licensing & Compliance MIS",
        slug: "ministry-energy-department-explosives-licensing-mis",
        description: "In partnership with the Petroleum Division, IT Artificer designed and implemented a national MIS for explosives licensing and regulatory compliance.",
        icon: "FileKey",
    },
];
